#定义dev开发环境下的配置
server:
  #配置服务启动端口号
  port: 8111
spring:
  #配置数据库链接
  datasource:
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用户名
    username: RYSTARS(hfe5OllBfO+rZsCD4NUwOw==)
    #密码
    password: RYSTARS(LaDjX+pgbKXd3s5ePIn8fQVMi1zaIqu0)
    #url
    url: RYSTARS(l0cKU/p4Ge5EkaURaPFI76gnzVgNSNuJ6USgy0fcEF6B9R8OjDPI4LIFycfXgui3)
    #定义数据源 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #多数据源用来区分名称
      name: dev
      #初始化时建立连接的个数
      initialSize: 5
      #最小连接数 与初始数相同
      minIdle: 5
      #最大连接池数量
      maxActive: 300
      #	获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，
      #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      maxWait: 60000
      #检查空闲连接的频率，单位毫秒, 非正整数时表示不进行检查
      timeBetweenEvictionRunsMillis: 60000
      #连接保持空闲而不被驱逐的最长时间
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql
      validationQuery: SELECT 1
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，
      #比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: false
      #每个连接最多缓存多少个SQL
      maxPoolPreparedStatementPerConnectionSize: 20
      #连接属性 记录慢SQL
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个datasource监控数据
      use-global-data-source-stat: true
      #配置监控统计拦截的filters，stat:监控统计 log4j:日志记录 wall:防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority 则导入 log4j 依赖即可
      filters: stat,wall,slf4j
      # 配置DruidStatFilter 监控web
      web-stat-filter:
        enabled: true
        #过滤所有url
        url-pattern: /*
        #配置不用拦截的资源
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet 监控页功能
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456