#多环境配置文件下 选取配置文件 不同配置文件是互补的状态
spring:
  profiles:
    active: dev
#定义公共配置
server:
  servlet:
    context-path: /rystars
#mybatis配置
mybatis:
  #配置扫描xml路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #配置类型别名
  type-aliases-package: com.rystars.mall.admin.**.bean
  #打印执行SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件配置
page helper:
  #配置使用的方言 不配置会自动检测
  helper-dialect: mysql
  #使用参数合理化 如果传入错误的 开始 结束页数,会返回第一页或最后一页，false返回空。
  reasonable: true
#mybatis xml文件热加载配置
mybatis-xml-reload:
  # 是否开启 xml 热更新，true开启，false不开启，默认为false
  enabled: true
  # xml文件路径，可以填写多个，逗号分隔。
  # eg: `classpath*:mapper/**/*Mapper.xml,classpath*:other/**/*Mapper.xml`
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#swagger配置
springdoc:
  swagger-ui:
    #配置swagger-ui请求路径
    path: swagger
    #API的排序方式 alpha按字母排序
    tags-sorter: alpha
    #按HTTP方式排序
    #operations-sorter: method
  #需要生成接口的接口路径
  paths-to-match: /pms/**,/cms/**
#使用jasypt对配置文件加密
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    #配置加密算法
    algorithm: PBEWithMD5AndDES
    #解析的字符
    property:
      prefix: RYSTARS(
      suffix: )
    #加密口令
#    方式一：直接作为程序启动时的命令行参数来带入 java -jar yourproject.jar --jasypt.encryptor.password=xxx
#    方式二：直接作为程序启动时的应用环境变量来带入VM java -Djasypt.encryptor.password=xxx -jar yourproject.jar
#    方式三：甚至可以作为系统环境变量的方式来带入 jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
#    password: ${JASYPT_ENCRYPTOR_PASSWORD:}