#定义dev开发环境下的配置
server:
  #配置服务启动端口号
  port: 8111
spring:
  #配置数据库链接
  datasource:
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用户名
    username: RYSTARS(jS3iLwHJfrEwfbUnWsdRqg==)
    #密码
    password: RYSTARS(2BjOUJWqzoBt86HdfEUqK8jZt9mKtUAn)
    #url
    #jdbc:mysql://43.138.200.193:3306/mall
    url: RYSTARS(0tNrK2leWgKzd7wS4vgqF0MoJWyMmwr5T8HjbGR39mpY0Jg4GYCmt70uUzp51S+i)
  data:
    #配置redis
    redis:
      #ip
      host: RYSTARS(jN78+ccE4d1dxMLx/orQiHRTUTVt1ftR)
      #端口
      port: 6379
      #密码
      password: RYSTARS(U19UhBPsaAH75CLKf5wUlA==)
      #数据库
      database: 0
      #配置连接池
      lettuce:
        pool:
          #连接池的最小连接数
          min-idle: 0
          #连接池的最大连接数
          max-active: 8
          #连接池最大阻塞等待时间 负值表示没有限值
          max-wait: -1ms