#定义dev开发环境下的配置
server:
  #配置服务启动端口号
  port: 8111
spring:
  #配置数据库链接
  datasource:
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用户名
    username: RYSTARS(hfe5OllBfO+rZsCD4NUwOw==)
    #密码
    password: RYSTARS(LaDjX+pgbKXd3s5ePIn8fQVMi1zaIqu0)
    #url
    url: RYSTARS(l0cKU/p4Ge5EkaURaPFI76gnzVgNSNuJ6USgy0fcEF6B9R8OjDPI4LIFycfXgui3)
  data:
    #配置redis
    redis:
      #ip
      host: RYSTARS(RETrFY7PJh1pwdZT+P5LOitnr5Q+2q3k)
      #端口
      port: 6379
      #密码
      password: RYSTARS(pN50YeE6ElX9v87MGiF3EQ==)
      #数据库
      database: 0
      #配置连接池
      lettuce:
        pool:
          #连接池的最小连接数
          min-idle: 0
          #连接池的最大连接数
          max-active: 8
          #连接池最大阻塞等待时间 负值表示没有限值
          max-wait: -1ms